# This is a basic workflow to help you get started with Actions

name: A3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'a3.h'
      - 'a3.cpp'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'a3.h'
      - 'a3.cpp'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v3
        with:
          repository: seneca-testers/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy cpp tester files
        run: cp ./tester/btp500/f2022/a3tester.cpp ./

      - name: Copy timer files files
        run: cp ./tester/btp500/f2022/timer.* ./

      - name: Copy timer dictionary file
        run: cp ./tester/btp500/f2022/a3dictionary.txt ./

      - name: Copy assignment files
        run: cp ./assignment/a3.h ./

      - name: Copy assignment files
        run: cp ./assignment/a3.cpp ./


      # Runs a single command using the runners shell
      - name: Compile
        run: c++ a3.cpp a3tester.cpp timer.cpp -std=c++0x -o a3

      # Runs a set of commands using the runners shell
      - name: Run
        run: timeout 120 ./a3
 
